access_key: "zl77yJli1I5rFneKDLInIgSvjHt8tBsB"
# ad_stat_url: "http://120.77.180.18:8080/ad/go"
ad_stat_url: "http://ad.echomoment.cn/ad/go"
debug: False
db:
  mongo:
    host: "localhost"
    port: 27017
    database_test: "ad_test"
    database: "ad"
    collections:
      ads: "ads"
      exhibitions: "exhibitions"
      clicks: "clicks"
